config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/welcome/markets' => 'welcome#index_markets'
  get '/welcome/markets/:id' => 'welcome#show_market', as: 'show_market'

  resources :markets do
    resources :vendors
  end

  resources :vendors do
    resources :products
    resources :sales
  end

end

app/models/market.rb
class Market < ActiveRecord::Base
  has_many :vendors
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :vendor
  has_many :sales

  def archive
    update(archived: true)
  end

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :vendor
  belongs_to :product

  def self.format_input(amount_string)
    amount_string.delete("$").to_f * 100
  end

  def self.sum_amount(collection_of_sales)
    collection_of_sales.reduce(0){ |sum, sale| sum + sale.amount }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :markets
  has_many :vendors, through: :markets
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  belongs_to :market
  has_many :products
  has_many :sales

  def self.current_month
    Time.now.month
  end

  def current_month_sales
    sales.where(:purchase_time => Time.now.beginning_of_month..Time.now.end_of_month)
  end

  def archive
    update(archived: true)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    
  end
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_nav
  before_action :set_market, only: [:show, :edit, :update]

  def index
    @markets = Market.all
  end

  def new
    @market = Market.new
  end

  def create
    market = Market.create(market_params)
    redirect_to market
  end

  def update
    @market.update(market_params)
    redirect_to @market
  end

  private
    def set_nav
      @nav = "market"
    end

    def set_market
      @market = Market.find(params[:id])
    end

    def market_params
      params.permit(market: [:name, :address, :city, :county, :state, :zip])[:market]
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_nav
  before_action :set_vendor, only: [:new, :create]

  def new
    @sale = Sale.new
    @product = Product.find(params[:product_id])
  end

  # Carly helped us figure out how to permit entering amounts as dollars
  def create
    sale = Sale.create(sale_params)
    redirect_to vendor_product_path(@vendor, Product.find(params[:sale][:product_id]))
  end

  private
    def set_nav
      @nav = "vendor"
    end

    def set_vendor
      @vendor = Vendor.find(params[:vendor_id])
    end

    def sale_params
      sale_params = params.permit(sale: [:amount, :purchase_time, :vendor_id, :product_id])[:sale]
      sale_params[:amount] = Sale.format_input(sale_params[:amount])

      sale_params
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    render :index
  end

  def show
    @markets = Market.all

    render :all_markets
  end

  def market_details
    @market_id =params[:id]
    @market = Market.find(@market_id)

    render :market_show
  end

  def name_sort
    @markets = Market.order(:name)

    render :all_markets
  end

  def city_sort
    @markets = Market.order(:city)

    render :all_markets
  end

  def state_sort
    @markets = Market.order(:state)

    render :all_markets
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_nav
  before_action :set_vendor, except: [:index, :new, :create]
  before_action :set_market, except: [:index, :show]

  def index
    @vendors = Vendor.all
  end

  def show
    if params[:market_id]
      set_market
      render 'show_from_markets'
    end

    @sales = @vendor.sales
    @current_month_sales = @vendor.current_month_sales
  end

  def new
    @vendor = Vendor.new
  end

  # vendors are only created, updated, or destroyed from market path
  def create
    vendor = Vendor.create(vendor_params)
    redirect_to market_vendor_path(@market, vendor)
  end

  def update
    @vendor.update(vendor_params)
    redirect_to market_vendor_path(@market, @vendor)
  end

  def destroy
    @vendor.archive
    redirect_to market_path(@market)
  end

  private
    def set_nav
      @nav = params[:market_id] ? "market" : "vendor"
    end

    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    def set_market
      @market = Market.find(params[:market_id])
    end

    def vendor_params
      params.permit(vendor: [:name, :num_employees, :market_id])[:vendor]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_nav

  def index_markets
    @markets = Market.all
  end

  def show_market
    @market = Market.find(params[:id])
    @vendors = @market.vendors
  end

  private
    def set_nav
      @nav = "welcome"
    end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index

  end

  def display_all_markets
    @markets = Market.all

    render :see_all_markets
  end

  def display_specific_market
    @market = Market.find(params[:id])

    render :specific_market
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datetime_helper.rb
module DatetimeHelper
  def format_datetime(timewithzone_object)
    timewithzone_object.strftime("%l:%M:%S %P on %m/%d/%Y")
  end
end

app/helpers/far_mars_helper.rb
module FarMarsHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/helpers/money_helper.rb
module MoneyHelper
  def format_money(amount_in_cents)
    number_to_currency(amount_in_cents.to_f/100)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendor_helper.rb
module VendorHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcome/home.html.erb
<h2>Would you like to look at Markets? or Vendors?</h2>
<br>
<%= button_to "Markets", markets_path, method: :get %>
<br>
<%= button_to "Vendors", vendors_path, method: :get %>
<br>


<%= render partial: "shared/market_list", locals: {user: "/show_users"} %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<h3>Log in:</h3>

<%= link_to "I am a market", markets_path, class: "log_in_button" %>
<%= link_to "I am a vendor", vendors_path, class: "log_in_button" %>
<%= link_to "View all markets", welcome_markets_path, id: "welcome_markets_button" %>

app/views/welcome/index_markets.html.erb
<h1>All Markets</h1>

<ul>
  <% @markets.each do |market| %>
    <li><%= link_to market.name, show_market_path(market) %></li>
  <% end %>
</ul>

app/views/welcome/show_market.html.erb
<% content_for :nav do %>
  <%= link_to 'All Markets', welcome_markets_path %>
<% end %>

<h1>Market Details</h1>

<%= render 'shared/show_market', { market: @market } %>

<h3>Vendors</h3>

<%= render 'shared/index_vendors', { vendors: @vendors } %>

app/views/welcomes/_header.html.erb
<div class ="link_back"><%= link_to "Back to Homepage", root_path %></div>

app/views/welcomes/index.html.erb
  <h1>FARMER'S MARKETS</h1>
  <h3>Here you can find information about farmer's markets in the United States.</h3>

  <div class = "nav">
    <ul>
      <li><%= link_to 'All markets', 'welcomes/markets' %></li>
      <li>Market <%= link_to 'Login', markets_path %></li>
      <li>Vendor <%= link_to 'Login', vendors_path %></li>
    </ul>
  </div>

  <div class="welcome_pic">
    <%= image_tag "welcome.png" %>
  </div>

  <div class = "section">

    <div class ="article1">
      <p>
       Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ultrices vitae nisl a convallis. Morbi nec nisi et augue accumsan pulvinar.      Nunc congue ligula accumsan, bibendum leo et, luctus ex. Aliquam erat volutpat. Sed lacinia est quis eros sagittis, in congue turpis posuere. Curabitur vehicula neque velit. Etiam viverra vulputate lorem, non pharetra lectus imperdiet non. Nam fringilla, nisl id blandit eleifend, dolor est elementum augue, nec luctus nisi elit id nulla. In laoreet nulla vitae rutrum ornare.
      </p>
    </div>

    <div class ="article2">
      <p>
       Nam tristique hendrerit egestas. Nullam pellentesque posuere tellus, id gravida urna sagittis quis. Nam efficitur pharetra dolor gravida bibendum. Aenean feugiat viverra lacus, nec consequat diam venenatis ut. Sed pellentesque arcu vitae libero iaculis, nec eleifend urna vulputate. Duis sit amet rhoncus erat, in egestas velit. Duis congue accumsan ex, id euismod magna pulvinar quis. Morbi viverra eros nec consequat porta. Nam in tempor tortor, id ultricies quam. Donec eu risus gravida, lacinia nulla non, semper tortor. Donec eu mi id lectus rhoncus placerat. Curabitur id nibh nec eros pulvinar vestibulum.
      </p>
    </div>

    <div class ="article3">
      <p>
       Sed dignissim nulla rhoncus, egestas ligula non, venenatis orci. Sed elementum quam vel purus vulputate ultricies. Phasellus ornare sem risus, in feugiat metus faucibus non. Sed pharetra tincidunt posuere. Vestibulum vitae euismod neque. Suspendisse nisi augue, porttitor ut imperdiet eu, aliquam sed enim. Phasellus molestie leo eu sapien molestie fringilla. Proin porta lobortis massa, in vestibulum elit consectetur sed. Aenean laoreet condimentum quam eleifend luctus. Suspendisse cursus lectus ex, a malesuada dui sollicitudin eget. Cras non viverra magna, et commodo neque.
     </p>
    </div>
  </div>

app/views/welcomes/see_all_markets.html.erb
<%= render partial: "header" %>

<h1>USA farmer's markets!</h1>

<div class = "markets_list">
  <ol>
    <% @markets.each do |market| %>
      <li><%= link_to "#{market.name}", "markets/#{market.id}" %></li>
    <% end %>
  </ol>
</div>

app/views/welcomes/specific_market.html.erb
<%= render partial: "header" %>

<div class = "specific_market_list">

  <p class="market_name"><%=@market.name  %></p>

  <p>Address:
    <%=@market.address  %>,
    <%=@market.city  %>,
    <%=@market.county  %>,
    <%=@market.state  %>.
    <%=@market.zip  %></p>
    <% vendors = @market.vendors %>

    <ol>Vendors:
      <% vendors.each do |v| %>
        <li><%= v.name %></li>
      <% end %>
    </ol>
</div>

<div class = "specific_market_pic">
  <%= image_tag "specific_market.png" %>
</div>