config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/welcome/markets' => 'welcome#index_markets'
  get '/welcome/markets/:id' => 'welcome#show_market', as: 'show_market'

  resources :markets do
    resources :vendors
  end

  resources :vendors do
    resources :products
    resources :sales
  end

end

app/models/market.rb
class Market < ActiveRecord::Base
  has_many :vendors
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :vendor
  has_many :sales

  def archive
    update(archived: true)
  end

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :vendor
  belongs_to :product

  def self.format_input(amount_string)
    amount_string.delete("$").to_f * 100
  end

  def self.sum_amount(collection_of_sales)
    collection_of_sales.reduce(0){ |sum, sale| sum + sale.amount }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :markets
  has_many :vendors, through: :markets
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  belongs_to :market
  has_many :products
  has_many :sales

  def self.current_month
    Time.now.month
  end

  def current_month_sales
    sales.where(:purchase_time => Time.now.beginning_of_month..Time.now.end_of_month)
  end

  def archive
    update(archived: true)
  end
end

app/controllers/far_mars_controller.rb
class FarMarsController < ApplicationController

  def index
    @page = "FarMar Welcome"
    @all_markets = Market.all
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    
  end
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_nav
  before_action :set_market, only: [:show, :edit, :update]

  def index
    @markets = Market.all
  end

  def new
    @market = Market.new
  end

  def create
    market = Market.create(market_params)
    redirect_to market
  end

  def update
    @market.update(market_params)
    redirect_to @market
  end

  private
    def set_nav
      @nav = "market"
    end

    def set_market
      @market = Market.find(params[:id])
    end

    def market_params
      params.permit(market: [:name, :address, :city, :county, :state, :zip])[:market]
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_nav
  before_action :set_vendor, only: [:new, :create]

  def new
    @sale = Sale.new
    @product = Product.find(params[:product_id])
  end

  # Carly helped us figure out how to permit entering amounts as dollars
  def create
    sale = Sale.create(sale_params)
    redirect_to vendor_product_path(@vendor, Product.find(params[:sale][:product_id]))
  end

  private
    def set_nav
      @nav = "vendor"
    end

    def set_vendor
      @vendor = Vendor.find(params[:vendor_id])
    end

    def sale_params
      sale_params = params.permit(sale: [:amount, :purchase_time, :vendor_id, :product_id])[:sale]
      sale_params[:amount] = Sale.format_input(sale_params[:amount])

      sale_params
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    render :index
  end

  def show
    @markets = Market.all

    render :all_markets
  end

  def market_details
    @market_id =params[:id]
    @market = Market.find(@market_id)

    render :market_show
  end

  def name_sort
    @markets = Market.order(:name)

    render :all_markets
  end

  def city_sort
    @markets = Market.order(:city)

    render :all_markets
  end

  def state_sort
    @markets = Market.order(:state)

    render :all_markets
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_nav
  before_action :set_vendor, except: [:index, :new, :create]
  before_action :set_market, except: [:index, :show]

  def index
    @vendors = Vendor.all
  end

  def show
    if params[:market_id]
      set_market
      render 'show_from_markets'
    end

    @sales = @vendor.sales
    @current_month_sales = @vendor.current_month_sales
  end

  def new
    @vendor = Vendor.new
  end

  # vendors are only created, updated, or destroyed from market path
  def create
    vendor = Vendor.create(vendor_params)
    redirect_to market_vendor_path(@market, vendor)
  end

  def update
    @vendor.update(vendor_params)
    redirect_to market_vendor_path(@market, @vendor)
  end

  def destroy
    @vendor.archive
    redirect_to market_path(@market)
  end

  private
    def set_nav
      @nav = params[:market_id] ? "market" : "vendor"
    end

    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    def set_market
      @market = Market.find(params[:market_id])
    end

    def vendor_params
      params.permit(vendor: [:name, :num_employees, :market_id])[:vendor]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_nav

  def index_markets
    @markets = Market.all
  end

  def show_market
    @market = Market.find(params[:id])
    @vendors = @market.vendors
  end

  private
    def set_nav
      @nav = "welcome"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datetime_helper.rb
module DatetimeHelper
  def format_datetime(timewithzone_object)
    timewithzone_object.strftime("%l:%M:%S %P on %m/%d/%Y")
  end
end

app/helpers/far_mars_helper.rb
module FarMarsHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/helpers/money_helper.rb
module MoneyHelper
  def format_money(amount_in_cents)
    number_to_currency(amount_in_cents.to_f/100)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendor_helper.rb
module VendorHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/vendors/_dashboard.html.erb
< <%= link_to "Dashboard", "/vendors/#{ params[:vendor_id] || params[:id] }/dashboard", title: "Go back to the Dashboard." %>

app/views/vendors/_form.html.erb
<%= form_for [ @market, @vendor ] do |f| %>
  <%= f.label :name, "Vendor name:" %>
  <%= f.text_field :name, required: :true %>

  <%= f.label :num_employees, "Number of employees:" %>
  <%= f.text_field :num_employees %>

  <%= f.hidden_field :market_id, value: params[:market_id] %>

  <%= f.submit class: "button" %>
<% end %>

app/views/vendors/_products.html.erb
< <%= link_to "Products", "/vendors/#{ params[:vendor_id] || params[:id] }/products", title: "Go back to the products list." %>

app/views/vendors/_vendor_form.html.erb
<fieldset>
  <legend><%= legend %></legend>

  <%= form_for @vendor, url: url, method: method, html: {class: "forms"} do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, required: :true %>

    <%= f.label "Number of Employees" %>
    <%= f.text_field :num_employees %>

    <%= f.hidden_field(id, :value => "#{value}") %>

    <%= f.submit %>

  <% end %>

</fieldset>

app/views/vendors/add_vendor.html.erb
<%= link_to "Go back to market", market_path("#{params[:market_id]}") %>

<h1>Add new vendor</h1>

<%= form_for @vendor do |v| %>
 <fieldset>
   <legend>New vendor</legend>
   <%= v.label :name %>
   <%= v.text_field :name %>

   <%= v.label :no_of_employees %>
   <%= v.text_field :no_of_employees %>

   <%= v.label :market_id %>
   <%= v.text_field :market_id, :value => params[:market_id] %>
 </fieldset>

 <%= v.submit 'Submit new vendor' %>
<% end %>

app/views/vendors/by_market.html.erb
<%= render "shared/header" %>
<main>
  <%= render "shared/each_vendor" %>
  <h3> <%= link_to "Edit Vendor", edit_by_market_path %> </h3>
  <h3> <%= link_to "Delete Vendor", by_market_path, method: :delete, data: { confirm: "Are you sure?"} %> </h3>
</main>
<%= render "shared/footer" %>

app/views/vendors/edit.html.erb
<h1>Edit Vendor</h1>

<%= render 'form' %>

app/views/vendors/edit_vendor.html.erb
<%= link_to "Back to vendor", market_vendor_path("#{@vendor.market_id}", "#{@vendor.id}") %>

<%= form_for @vendor do |v| %>
 <fieldset>
   <legend>New task</legend>
   <%= v.label :name %>
   <%= v.text_field :name %>

   <%= v.label :no_of_employees %>
   <%= v.text_field :no_of_employees %>

   <%= v.label :market_id %>
   <%= v.text_field :market_id %>
 </fieldset>

 <%= v.submit 'Save changes' %>
<% end %>

app/views/vendors/index.html.erb
<h1>Pick a Vendor</h1>

<ul>
  <% @vendors.each do |vendor| %>
    <% unless vendor.archived %>
      <li><%= link_to vendor.name, vendor %></li>
    <% end %>
  <% end %>
</ul>

app/views/vendors/show.html.erb
<h1>Vendor Details</h1>

<%= render 'vendor_attributes' %>

<h3>Products</h3>

<%= link_to 'Create a new product for this vendor', new_vendor_product_path(@vendor),
    class: "button" %>

<ul>
  <% @vendor.products.each do |product| %>
    <% unless product.archived %>
      <li>
        <%= link_to product.name, vendor_product_path(@vendor, product),
          class: "list_element" %>
        <%= link_to "Edit", edit_vendor_product_path(@vendor, product),
          class: "inline_button" %>
        <%= button_to "Delete", vendor_product_path(@vendor, product),
          class: "inline_button",
          method: :delete,
          data: { confirm: "Are you sure you want to delete this product?" } %>
        <%= link_to "+ Sale", new_vendor_sale_path(@vendor, :product_id => product.id),
          class: "inline_button" %>
      </li>
    <% end %>
  <% end %>
</ul>

<h3>All Sales</h3>

<%= render 'shared/sales_table', { sales: @sales } %>

<h3>Current Month's Sales</h3>

<%= render 'shared/sales_table', { sales: @current_month_sales } %>

app/views/vendors/show_from_vendors.html.erb
<h1>Ima Vendor!</h1>

<ul>
  <li>Name: <%= @vendor.name %></li>
  <li>Number of Employees: <%= @vendor.num_employees %></li>
  <li>Sells at: <%= @vendor.market.name %></li>
</ul>

<h3>Products</h3>

<%= link_to 'Create a new product for this vendor', new_vendor_product_path(@vendor) %>

<ul>
  <% @vendor.products.each do |product| %>
    <li><%= link_to product.name, vendor_product_path(@vendor, product) %></li>
  <% end %>
</ul>

<!-- # list of products

# see my sales
# - total sales amount

# see current month's sales
# - current month sales amount -->

app/views/vendors/vendor_not_found.html.erb
<div class="error-wrapper">
  <p class="error">
    No vendor was found with the identification number you provided.
    Please check your number and try this login again.
  </p>
</div>

<h2 class="btn-identity">
  <%= link_to "Go back to the login page.", "/vendor", title: "Go back to the login page." %>
</h2>

app/views/vendors/vendor_portal.html.erb
<section class="homepage">
  <div>
      <h1>Welcome back <%= @vendor.name %>!</h1>
      <h3>I would like to...</h3>
      <%= link_to "Add/Edit Products", market_vendor_products_path(@vendor.market_id, @vendor.id), class: "button_link" %>
      <%= link_to "Add a Sale", new_market_vendor_sale_path(@vendor.market_id, @vendor.id), class: "button_link" %>
  </div>


  <div>
    <h1>Sales Information</h1>
    <h3>Total Sales: <%= number_to_currency(@total_sales) %></h3>
    <table>
      <thead>
        <tr>
          <th>
            Amount
          </th>
          <th>
            Purchase Date
          </th>
          <th>
            Product
          </th>
        </tr>
      </thead>
      <tbody>
        <% @vendor.sales.each do |sale| %>
        <tr>
          <td>
            <%= number_to_currency(sale.amount / 100.0) %>
          </td>
        <td>
          <%= sale.purchase_time.strftime("%m/%d/%Y") %>
        </td>
        <td>
          <%= (Product.find(sale.product_id)).name %>
        </td>
        <% end %>
        </tr>
      </tbody>
    </table>

    <h3>Monthly Sales for <%= Date.today.strftime("%B") %>: <%= number_to_currency(@month_sales) %></h3>
    <table>
      <thead>
        <tr>
          <th>
            Amount
          </th>
          <th>
            Purchase Date
          </th>
          <th>
            Product
          </th>
        </tr>
      </thead>
      <tbody>
        <% @vendor.sales.each do |sale| %>
          <% if sale.purchase_time.to_date.strftime("%Y-%m") == @date_today %>
            <tr>
              <td>
                <%= number_to_currency(sale.amount / 100.0) %>
              </td>
              <td>
                <%= sale.purchase_time.strftime("%m/%d/%Y") %>
              </td>
              <td>
                <%= (Product.find(sale.product_id)).name %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/vendors/vendor_show.html.erb
<p><%= link_to "<< return to market", "#{market_path(@vendor.market_id)}" %></p>
<h1> <%= @vendor.name %> </h1>

<table>
  <thead>
    <tr>
      <th>
        ID
      </th>
      <th>
        Market
      </th>
      <th>
        # of Employees
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        <%= @vendor.id %>
      </td>
      <td>
        <%= (Market.find(@vendor.market_id)).name %>
      </td>
      <td>
        <%= @vendor.no_of_employees %>
      </td>
      <td>
        <%= link_to "Edit", edit_market_vendor_path(@vendor.market_id, @vendor.id) %>
      </td>
      <td>
        <%= link_to "Delete", market_vendor_path(@vendor.market_id, @vendor.id), :method => :delete %>
      </td>
    </tr>
  </tbody>
</table>