config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/welcome/markets' => 'welcome#index_markets'
  get '/welcome/markets/:id' => 'welcome#show_market', as: 'show_market'

  resources :markets do
    resources :vendors
  end

  resources :vendors do
    resources :products
    resources :sales
  end

end

app/models/market.rb
class Market < ActiveRecord::Base
  has_many :vendors
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :vendor
  has_many :sales

  def archive
    update(archived: true)
  end

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :vendor
  belongs_to :product

  def self.format_input(amount_string)
    amount_string.delete("$").to_f * 100
  end

  def self.sum_amount(collection_of_sales)
    collection_of_sales.reduce(0){ |sum, sale| sum + sale.amount }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :markets
  has_many :vendors, through: :markets
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  belongs_to :market
  has_many :products
  has_many :sales

  def self.current_month
    Time.now.month
  end

  def current_month_sales
    sales.where(:purchase_time => Time.now.beginning_of_month..Time.now.end_of_month)
  end

  def archive
    update(archived: true)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    
  end
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_nav
  before_action :set_market, only: [:show, :edit, :update]

  def index
    @markets = Market.all
  end

  def new
    @market = Market.new
  end

  def create
    market = Market.create(market_params)
    redirect_to market
  end

  def update
    @market.update(market_params)
    redirect_to @market
  end

  private
    def set_nav
      @nav = "market"
    end

    def set_market
      @market = Market.find(params[:id])
    end

    def market_params
      params.permit(market: [:name, :address, :city, :county, :state, :zip])[:market]
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_nav
  before_action :set_vendor, only: [:new, :create]

  def new
    @sale = Sale.new
    @product = Product.find(params[:product_id])
  end

  # Carly helped us figure out how to permit entering amounts as dollars
  def create
    sale = Sale.create(sale_params)
    redirect_to vendor_product_path(@vendor, Product.find(params[:sale][:product_id]))
  end

  private
    def set_nav
      @nav = "vendor"
    end

    def set_vendor
      @vendor = Vendor.find(params[:vendor_id])
    end

    def sale_params
      sale_params = params.permit(sale: [:amount, :purchase_time, :vendor_id, :product_id])[:sale]
      sale_params[:amount] = Sale.format_input(sale_params[:amount])

      sale_params
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    render :index
  end

  def show
    @markets = Market.all

    render :all_markets
  end

  def market_details
    @market_id =params[:id]
    @market = Market.find(@market_id)

    render :market_show
  end

  def name_sort
    @markets = Market.order(:name)

    render :all_markets
  end

  def city_sort
    @markets = Market.order(:city)

    render :all_markets
  end

  def state_sort
    @markets = Market.order(:state)

    render :all_markets
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_nav
  before_action :set_vendor, except: [:index, :new, :create]
  before_action :set_market, except: [:index, :show]

  def index
    @vendors = Vendor.all
  end

  def show
    if params[:market_id]
      set_market
      render 'show_from_markets'
    end

    @sales = @vendor.sales
    @current_month_sales = @vendor.current_month_sales
  end

  def new
    @vendor = Vendor.new
  end

  # vendors are only created, updated, or destroyed from market path
  def create
    vendor = Vendor.create(vendor_params)
    redirect_to market_vendor_path(@market, vendor)
  end

  def update
    @vendor.update(vendor_params)
    redirect_to market_vendor_path(@market, @vendor)
  end

  def destroy
    @vendor.archive
    redirect_to market_path(@market)
  end

  private
    def set_nav
      @nav = params[:market_id] ? "market" : "vendor"
    end

    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    def set_market
      @market = Market.find(params[:market_id])
    end

    def vendor_params
      params.permit(vendor: [:name, :num_employees, :market_id])[:vendor]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_nav

  def index_markets
    @markets = Market.all
  end

  def show_market
    @market = Market.find(params[:id])
    @vendors = @market.vendors
  end

  private
    def set_nav
      @nav = "welcome"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datetime_helper.rb
module DatetimeHelper
  def format_datetime(timewithzone_object)
    timewithzone_object.strftime("%l:%M:%S %P on %m/%d/%Y")
  end
end

app/helpers/far_mars_helper.rb
module FarMarsHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/helpers/money_helper.rb
module MoneyHelper
  def format_money(amount_in_cents)
    number_to_currency(amount_in_cents.to_f/100)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendor_helper.rb
module VendorHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/markets/_market_form.html.erb
<%= form_for @market, html: {class: "forms"} do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, required: :true %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zip %>
  <%= f.text_field :zip %>

  <%= f.submit %>

  <% end %>

app/views/markets/add_market.html.erb
<%= link_to "Go back to markets", markets_path %>

<h1>Add new market</h1>

<div class= "form">
  <%= form_for @market do |m| %>
  <fieldset>
    <legend>New task</legend>
    <%= m.label :name %>
    <%= m.text_field :name %>

    <%= m.label :address %>
    <%= m.text_field :address %>

    <%= m.label :city %>
    <%= m.text_field :city %>

    <%= m.label :county %>
    <%= m.text_field :county %>

    <%= m.label :state %>
    <%= m.text_field :state %>

    <%= m.label :zip %>
    <%= m.text_field :zip %>
  </fieldset>
  
  <%= m.submit 'Add new market' %>
 <% end %>
</div>

<div class="welcome_pic">
  <%= image_tag "welcome.png" %>
</div>

app/views/markets/by_market.html.erb
<body class="market-background">
  <h1>Vendors for <%= @market.name %></h1>
  <%= button_to "Add Another Vendor", new_market_vendor_path(@market.id), method: :get, class: "button" %>
  <div class="text_box">
    <table>
      <tr>
        <th>Name</th>
        <th>Number of Employees</th>
        <th></th>
        <th></th>
      </tr>
      <% @vendors.each do |vendor| %>
      <tr>
        <td><%=vendor.name%></td>
        <td><%=vendor.num_of_employees%></td>
        <td><%=button_to "Edit Vendor", edit_market_vendor_path(@market.id, vendor.id), method: :get, class: "inner_button" %>
        <td><%=button_to "Delete Vendor", market_vendor_path(@market.id, vendor.id), method: :delete, data: {confirm: "Are you sure?"}, class: "inner_button" %></td>
      </tr>
      <% end %>
    </table>
  </div>
</body>

app/views/markets/edit.html.erb
<h1>Edit Market</h1>

<%= render 'form' %>

app/views/markets/edit_market.html.erb
<%= link_to "Back to market", market_path("#{@market.id}") %>

<div class= "form">
  <%= form_for @market do |m| %>
    <fieldset>
      <legend>New task</legend>
      <%= m.label :name %>
      <%= m.text_field :name %>

      <%= m.label :address %>
      <%= m.text_field :address %>

      <%= m.label :city %>
      <%= m.text_field :city %>

      <%= m.label :county %>
      <%= m.text_field :county %>

      <%= m.label :state %>
      <%= m.text_field :state %>

      <%= m.label :zip %>
      <%= m.text_field :zip %>
    </fieldset>

    <%= m.submit 'Save changes' %>
  <% end %>
</div>

<div class="welcome_pic">
  <%= image_tag "welcome.png" %>
</div>

app/views/markets/error.html.erb
<% content_for :breadcrumbs do %>
  <%= render partial: "/markets/dashboard" %>
<% end %>

<div class="error-wrapper">
  <p class="error">Error: Market not created or updated.</p>

  <p class="error-details">
    A market must have all attribute fields filled out.
  </p>
</div>

app/views/markets/index.html.erb
<h1>Pick a Market</h1>

<%= link_to "Create a new market", new_market_path, class: "button" %>

<ul>
  <% @markets.each do |market| %>
    <li><%= link_to market.name, market %></li>
  <% end %>
</ul>

app/views/markets/market_not_found.html.erb
<div class="error-wrapper">
  <p class="error">
    No market was found with the identification number you provided.
    Please check your number and try this login again.
  </p>
</div>

<h2 class="btn-identity">
  <%= link_to "Create New Market", "/markets/new", title: "Create & log in as a a new market." %>
</h2>
<h2 class="btn-identity">
  <%= link_to "Login Page", "/market", title: "Go back to the login page." %>
</h2>

app/views/markets/markets.html.erb
<%= link_to "<< return to main page", "/" %>
<h1>All Markets</h1>
<%= form_tag({controller:'markets', action: 'search'}, method: "get") do %>
<%= text_field_tag :search, params[:search], id: 'search_field', placeholder: "Search by Name" %>
<%= submit_tag "Search" %>
<% end %>
<p>
  <%= link_to "+ Add a Market", new_market_path %>
</p>
<table>
  <thead>
    <tr>
      <th>
        Name <%= link_to "&#8595".html_safe, "/markets_/name_sort" %>
      </th>
      <th>
        Address
      </th>
      <th>
        City <%= link_to "&#8595".html_safe, "/markets_/city_sort" %>
      </th>
      <th>
        State <%= link_to "&#8595".html_safe, "/markets_/state_sort" %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @markets.each do |market|%>
    <tr>
      <td>
        <%= link_to "#{market.name}", market_path(market.id) %>
      </td>
      <td>
        <%= market.address %>
      </td>
      <td>
        <%= market.city %>
      </td>
      <td>
        <%= market.state %>
      </td>
      <td>
        <%= link_to "Edit", edit_market_path(market.id) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/markets/new.html.erb
<h1>Create a New Market</h1>

<%= render 'form' %>

app/views/markets/show.html.erb
<h1>Market Details</h1>

<%= render 'shared/show_market', { market: @market } %>

<%= link_to "Edit this market", edit_market_path, class: "button" %>

<h3>Vendors</h3>

<%= link_to "Create a new vendor for this market", new_market_vendor_path(@market),
  class: "button" %>

<ul>
  <% @market.vendors.each do |vendor| %>
    <% unless vendor.archived %>
      <li>
        <%= link_to vendor.name, market_vendor_path(@market, vendor) %>
        <%= link_to 'Edit', edit_market_vendor_path(@market, vendor),
          class: "inline_button" %>
        <%= button_to 'Delete', market_vendor_path(@market, vendor),
          class: "inline_button", method: :delete,
          data: { confirm: "Are you sure you want to delete this vendor?" } %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/markets/show_users.html.erb
<h1>Market </h1>


<%= render partial: "shared/market_details", locals: {

  details: {

    "Market ID"   => @market.id,
    "Market Name" => @market.name,
    "Address"     => @market.street_address,
    "City"        => @market.city,
    "State"       => @market.state,
    "Zip"         => @market.zip,
    "County"      => @market.county

  }
} %>



<h2>List of Vendors</h2>

<table border "1">

  <tr>
    <th>
      Vendor ID
    </th>
    <th>
      Vendor Name
    </th>
    <th>
      No. of Employees
    </th>
    <th>
      Market ID
    </th>

  </tr>

<% @vendors.each do |vendor| %>
  <tr>
    
    <td>
      <%= vendor.id %>
    </td>
    <td>
      <%= vendor.name %>
    </td>
    <td>
      <%= vendor.no_of_employees %>
    </td>
    <td>
      <%= vendor.market_id %>
    </td>
   
  </tr>
  <% end %>
</table>
<br>

app/views/markets/vendors_index.html.erb
<%= render 'shared/show_vendors' %>

app/views/markets/view.html.erb
<h1><%= @market.name %></h1>

<table>
  <tr>
    <th> ID </th>
    <th> Address </th>
    <th> City </th>
    <th> County </th>
    <th> State </th>
    <th> Zip </th>
    <th> Established </th>
  </tr>

  <tr>
    <td> <%= @market.id %> </td>
    <td> <%= @market.address %> </td>
    <td> <%= @market.city %> </td>
    <td> <%= @market.county %> </td>
    <td> <%= @market.state %> </td>
    <td> <%= @market.zip %> </td>
    <td> <%= @market.created_at %> </td>
  </tr>

</table>

<h3>VENDORS</h3>
<table>
  <tr>
    <th> Name </th>
  </tr>
  <% @market_vendors.each do |vendor| %>
  <tr>
    <td> <%= vendor.name %> </td>
  </tr>
  <% end %>
</table>

app/views/sales/_form.html.erb
<%= form_for [@vendor, @sale] do |f| %>
  <%= f.label :amount, "Sale amount:" %>
  <%= f.text_field :amount, required: :true, placeholder: "$0.00" %>

  <%= f.label :purchase_time, "Time and date of sale:" %>
  <%= f.datetime_local_field :purchase_time, required: :true %>

  <%= f.hidden_field :vendor_id, value: params[:vendor_id] %>
  <%= f.hidden_field :product_id, value: @product.id %>

  <%= f.submit class: "button" %>
<% end %>

app/views/sales/_sale_form.html.erb
<%= form_for @sale, url: url do |f| %>

  <fieldset>
    <legend>Sale Details</legend>
    <%= f.label :amount, "Amount: " %>
    <%= f.text_field :amount, :required => true %>

    <%= f.label :products %>
    <%= f.collection_select :product_id, @products, :id, :name %>

    <%= f.hidden_field :purchase_time, :value => Time.now %> <!-- New form-->
    <%= f.hidden_field :vendor_id, :value => params[:vendor_id] %> <!-- Edit form -->
  </fieldset>
    <%= f.submit 'Submit' %>
<% end %>

app/views/sales/add_sale.html.erb
<h1>Add new sale</h1>

<%= form_for @sale, url: vendor_product_sales_path("#{params[:vendor_id]}", "#{params[:product_id]}") do |s| %>
  <fieldset>
    <legend>New product</legend>
    <%= s.label :amount %>
    <%= s.text_field :amount %>

    <%= s.label :purchase_time %>
    <%= s.date_field :purchase_time %>

    <%= s.label :vendor_id %>
    <%= s.text_field :vendor_id, :value => params[:vendor_id] %>

    <%= s.label :product_id %>
    <%= s.text_field :product_id, :value => params[:product_id] %>
  </fieldset>

 <%= s.submit 'Submit new sale' %>
<% end %>

app/views/sales/current_month_sales.html.erb
<%= render 'shared/header' %>

<h1><%= @vendor.name %>:</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Sale Amount</th>
    <th>Purchase Date/Time</th>
  </tr>

  <% if @current_month.length != 0 %>
    <% @current_month.each do |sale| %>
      <tr>
          <td><%= sale.product.name %></td>
          <td><%= number_to_currency(sale.amount / 100.00) %></td>
          <td><%= sale.purchase_time %></td>
          </td>
      </tr>
      <% end %>
  <% else %>
    <tr>
      <td><h3>You don't have any sales this month.</h3></td>
    </tr>
  <% end %>

  <tr>
    <td><h3>Total Sales in Current Month: <%= number_to_currency(Sale.current_month_total(@current_month) / 100.00) %></h3></td>
  </tr>
</table>

<%= link_to "Back to all sales", vendor_sales_path %>

<%= render "shared/footer" %>

app/views/sales/current_sales.html.erb
<%= link_to "Back to vendor", vendor_path("#{params[:vendor_id]}") %>

<p>Total sales: <%= "#{@current_sales}" %></p>

<table>
  <% @sales.each do |sale| %>
    <% if (sale.purchase_time.nil? == false) && (sale.purchase_time.month == Time.new.month) %>
      <tr>
         <td>Sale amount: <%= sale.amount  %></td>
        <td>Purchase time: <%= sale.purchase_time  %></td>
        <td>Vendor ID: <%= sale.vendor_id %></td>
        <td>Product: <%= sale.product.name  %></td>
      </tr>
    <% else %>
      <tr>
        <td>There are no sales for this month :(  </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/sales/empty.html.erb
<% content_for :breadcrumbs do %>
  <%= render partial: "/vendors/dashboard" %>
  <%= render partial: "/vendors/sales" %>
<% end %>

<h2 class="center">There are no sales available for this vendor for this month.</h2>

app/views/sales/error.html.erb
<% content_for :breadcrumbs do %>
  <%= render partial: "/vendors/dashboard" %>
  <%= render partial: "/vendors/sales" %>
<% end %>

<div class="error-wrapper">
  <p class="error">Error: Sale not created.</p>

  <p class="error-details">
    A sale must have a numeric value for its amount. A sale could be for 14.50 or
    25.82 but not for $14.50 or twenty five dollars and eighty-two cents. A sale
    must also have a valid date!
  </p>
</div>

app/views/sales/index.html.erb
<%= link_to "Back to vendor", vendor_path("#{params[:vendor_id]}") %>

<p>Total sales: <%= "#{@total_sales}" %></p>
  <table>
    <% @sales.each do |sale| %>
      <tr>
        <td>Sale amount: <%= sale.amount  %></td>
        <td>Purchase time: <%= sale.purchase_time  %></td>
        <td>Vendor ID: <%= sale.vendor_id %></td>
        <td>Product: <%= sale.product.name  %></td>
      </tr>
    <% end %>
  </table>

<!-- If we are coming from vendor > product > sale -->
<% if params[:product_id] %>
  <%= button_to "+ Sale", new_vendor_product_sale_path("#{@vendor.id}", "#{@product.id}"), method: "get" %>
<% end %>

app/views/sales/month_sales.html.erb
<%= render partial: "users/header", locals: { title: "Sales for the Month", link_name: "Back to Vendor", link_path: vendor_path(@vendor.id), second_link: false } %>

<table>

  <th>$ Amount</th>
  <th>Purchase Time</th>

  <% @month_sales.each do |sale| %>
  <tr>
   <td><%= number_to_currency(sale.amount / 100.00) %></td>
    <td><%= sale.purchase_time %></td>
  <tr>
<% end %>
</table>

<% unless @month_sales.length == 0 %>
  <p>Total month revenue: <%= number_to_currency(@month_revenue / 100.00) %></p>
<% else %>
  <p>There were no sales this month.</p>
<% end %>

app/views/sales/new.html.erb
<h1>Create a New Sale</h1>

<%= render 'form' %>

app/views/sales/sales_of_month.html.erb
<body class="vendor-background">
  <h1><%= Time.now.strftime("%B") %> Sales </h1>
  <div class="text_box">
    <% if @sales.empty? %>
      <p>There are no sales for this month</p>
    <% else%>
      <table>
        <tr>
          <th>Amount</th>
          <th>Purchase Time</th>
        </tr>
          <% total_sales = 0 %>
          <% @sales.each do |sale|%>
          <% total_sales += sale.amount %>
        <tr>
            <td>$<%= cents_to_dollars(sale.amount) %></td>
            <td><%= sale.purchase_time.strftime("%B, %d %Y") %></td>
        </tr>
          <% end %>
          <p>Total Sales: $<%= cents_to_dollars(total_sales) %></p>

      </table>
      <% end %>
  </div>
</body>

app/views/sales/show.html.erb
<h1><%= @vendor.name %></h1>

<h2><%= Time.now.strftime("%B") %> Sales</h2>

<h3>TRANSACTIONS</h3>
<table>
  <tr>
    <th> Product </th>
    <th> Amount </th>
    <th> Purchase Time </th>
  </tr>
  <% @month_vendor_sales.each do |sale| %>
  <tr>
    <% product_id = sale.product_id %>
    <% product = Product.find(product_id) %>

    <td> <%= product.name %> </td>
    
    <% amount = sale.amount / 100.00 %>
    <td> <%= number_to_currency(amount) %> </td>
    
    <td> <%= sale.purchase_time %> </td>
  </tr>
  <% end %>
</table>

app/views/users/_form.html.erb
<%= form_tag(controller: controller, action: "login", class: "login") do %>
  <div>
    <%= label_tag(:login_id, login_id) %>
    <%= text_field_tag(:login_id) %>
  </div>

  <div>
    <%= label_tag(:worthless_password, "Password:") %>
    <%= password_field_tag(:worthless_password) %>
  </div>

  <%= submit_tag("Log in", class: "submit") %>
<% end %>

app/views/users/_header.html.erb
<header>
  <h1><%= title %></h1>
</header>

<nav>
  <%= link_to link_name, link_path, :class => "nav_link" %>

  <% if second_link == true %>
    <%= link_to link_name2, link_path2, :class => "nav_link" %>
  <% end %>
</nav>

app/views/users/all_markets.html.erb
<%= link_to "<< return to main page", "/" %>
<h1>All Markets</h1>
<%= form_tag markets_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<table>
  <thead>
    <tr>
      <th>
        Name <%= link_to "&#8595".html_safe, "/all_markets_/name_sort" %>
      </th>
      <th>
        Address
      </th>
      <th>
        City <%= link_to "&#8595".html_safe, "/all_markets_/city_sort" %>
      </th>
      <th>
        County
      </th>
      <th>
        State <%= link_to "&#8595".html_safe, "/all_markets_/state_sort" %>
      </th>
      <th>
        Zip Code
      </th>
    </tr>
  </thead>
  <tbody>
    <% @markets.each do |market|%>
    <tr>
      <td>
        <%= link_to "#{market.name}", "/all_markets/#{market.id}" %>
      </td>
      <td>
        <%= market.address %>
      </td>
      <td>
        <%= market.city %>
      </td>
      <td>
        <%= market.county %>
      </td>
      <td>
        <%= market.state %>
      </td>
      <td>
        <%= market.zip.to_s.length == 5 ? market.zip : "" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/by_market.html.erb
<%= render "shared/header" %>
<main>
  <%= render "shared/each_market" %>
  <%= render "shared/vendor_list" %>
</main>
<%= render "shared/footer" %>

app/views/users/index.html.erb
<section class="homepage">
    <h1>Farmers Markets Interactive</h1>
    <h2>Welcome to FMI. You can view all markets, or let us know if you're a market or a vendor to make changes to your business.</h2>
    <p>are you a...</p>
      <%= link_to "MARKET", markets_path, class: "button_link" %>
      <%= link_to "VENDOR", vendor_portal_path, class: "button_link" %>
    <p>or would you like to <%= link_to "view all markets", controller: "users", action: "show" %>?</p>
</section>

app/views/users/market.html.erb
<section id="login-form" class="center">
  <header>
    <h1>Welcome to the Market Login</h1>
  </header>

  <%= render partial: "form", locals: { controller: "markets",
                                        login_id: "Market ID:" } %>

  <h2 class="btn-identity"><%= link_to "Create New Market", "/markets/new", title: "Create & log in as a a new market." %></h2>
</section>

app/views/users/market_show.html.erb
<%= link_to "<< return to markets", "/all_markets" %>
<h1> <%= @market.name%></h1>
<table>
  <thead>
    <tr>
      <th>
        Address
      </th>
      <th>
        City
      </th>
      <th>
        County
      </th>
      <th>
        State
      </th>
      <th>
        Zip Code
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= @market.address %>
      </td>
      <td>
        <%= @market.city %>
      </td>
      <td>
        <%= @market.county %>
      </td>
      <td>
        <%= @market.state %>
      </td>
      <td>
        <%= @market.zip %>
      </td>
    </tr>
  </tbody>
</table>
<h2>Vendors associated with <%= @market.name %></h2>
<% @market.vendors.each do |vendor| %>
<li>
  <%= vendor.name %>
</li>
<% end %>

app/views/users/markets.html.erb
<%= render "shared/header" %>
<main class="index_header">
  <%= render "shared/all_markets" %>
</main>
<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render 'shared/show_market' %>

app/views/users/vendor.html.erb
<section id="login-form" class="center">
  <header>
    <h1>Welcome to the Vendor Login</h1>
  </header>

  <%= render partial: "form", locals: { controller: "vendors",
                                        login_id: "Vendor ID:" } %>
</section>

app/views/users/vendors.html.erb
<%= render 'shared/show_vendors' %>

app/views/users/welcome.html.erb
<h1>Welcome!</h1>
<h2>Who are you?</h2>

<!-- later, links will need to be setting user role... -->
<div class="button_block">
  <div class="center_inline_block">
    <%= link_to 'Market', markets_path %>
  </div>
  <div class="center_inline_block">
    <%= link_to 'Vendor', vendors_path %>
  </div>
</div>

<div class="button_block">
  <%= link_to 'View Markets', markets_users_path %>
</div>