config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/welcome/markets' => 'welcome#index_markets'
  get '/welcome/markets/:id' => 'welcome#show_market', as: 'show_market'

  resources :markets do
    resources :vendors
  end

  resources :vendors do
    resources :products
    resources :sales
  end

end

app/models/market.rb
class Market < ActiveRecord::Base
  has_many :vendors
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :vendor
  has_many :sales

  def archive
    update(archived: true)
  end

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :vendor
  belongs_to :product

  def self.format_input(amount_string)
    amount_string.delete("$").to_f * 100
  end

  def self.sum_amount(collection_of_sales)
    collection_of_sales.reduce(0){ |sum, sale| sum + sale.amount }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :markets
  has_many :vendors, through: :markets
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  belongs_to :market
  has_many :products
  has_many :sales

  def self.current_month
    Time.now.month
  end

  def current_month_sales
    sales.where(:purchase_time => Time.now.beginning_of_month..Time.now.end_of_month)
  end

  def archive
    update(archived: true)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_nav
  before_action :set_vendor, only: [:new, :create]

  def new
    @sale = Sale.new
    @product = Product.find(params[:product_id])
  end

  # Carly helped us figure out how to permit entering amounts as dollars
  def create
    sale = Sale.create(sale_params)
    redirect_to vendor_product_path(@vendor, Product.find(params[:sale][:product_id]))
  end

  private
    def set_nav
      @nav = "vendor"
    end

    def set_vendor
      @vendor = Vendor.find(params[:vendor_id])
    end

    def sale_params
      sale_params = params.permit(sale: [:amount, :purchase_time, :vendor_id, :product_id])[:sale]
      sale_params[:amount] = Sale.format_input(sale_params[:amount])

      sale_params
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    render :index
  end

  def show
    @markets = Market.all

    render :all_markets
  end

  def market_details
    @market_id =params[:id]
    @market = Market.find(@market_id)

    render :market_show
  end

  def name_sort
    @markets = Market.order(:name)

    render :all_markets
  end

  def city_sort
    @markets = Market.order(:city)

    render :all_markets
  end

  def state_sort
    @markets = Market.order(:state)

    render :all_markets
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datetime_helper.rb
module DatetimeHelper
  def format_datetime(timewithzone_object)
    timewithzone_object.strftime("%l:%M:%S %P on %m/%d/%Y")
  end
end

app/helpers/far_mars_helper.rb
module FarMarsHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/helpers/money_helper.rb
module MoneyHelper
  def format_money(amount_in_cents)
    number_to_currency(amount_in_cents.to_f/100)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendor_helper.rb
module VendorHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_market_nav.html.erb
<%= link_to 'All Markets', markets_path %>

<%= link_to 'Market', market_path(@market) if params[:market_id] %>

<%= link_to 'Logout', :root %>

app/views/layouts/_vendor_nav.html.erb
<%= link_to 'All Vendors', vendors_path %>

<%= link_to 'Vendor', vendor_path(@vendor) if params[:vendor_id] %>
<%= link_to 'Product', vendor_product_path(@vendor, @product) if params[:product_id] %>

<%= link_to 'Logout', :root %>

app/views/layouts/_welcome_nav.html.erb
<%= link_to 'Home', :root %>

<%= yield :nav %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Far Mar | Alice &amp; Ashley</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <nav>
    <%= render "layouts/#{@nav}_nav" %>
  </nav>
</header>

<%= yield %>

</body>
</html>

app/views/shared/_all_markets.html.erb
  <table>
    <tr>
      <th>Market Name</th>
    </tr>
    <% @markets.each do |market| %>
    <tr>
        <td><%= link_to "#{market.name.titlecase}", "markets/#{market.id}" %> </td>
    </tr>
    <% end %>
  </table>

app/views/shared/_all_markets_table.html.erb
<h1>All Markets</h1>

<div class="button_block">
  <%= link_to "Back to Homepage", root_path, method: :get %>
</div>

<table>
<tr>
  <th>
    ID
  </th>
  <th>
    Name
  </th>
  <th>
    Address
  </th>
  <th>
    City
  </th>
  <th>
    County
  </th>
  <th>
    State
  </th>
  <th>
    Zip
  </th>
  <th class="center">
    Details
  </th>
</tr>
<tbody>
  <% @markets.each do |market| %>
  <tr>
    <td>
      <%= market.id %>
    </td>
    <td>
      <%= market.name %>
    </td>
    <td>
      <%= market.address %>
    </td>
    <td>
      <%= market.city %>
    </td>
    <td>
      <%= market.county %>
    </td>
    <td>
      <%= market.state %>
    </td>
    <td>
      <%= market.zip %>
    </td>
    <td class="center">
      <% if current_page?(controller: 'users', action: 'index',) %>
        <%= link_to "Details", controller: 'users', action: 'show', id: market.id %>
      <% elsif current_page?(controller: 'markets', action: 'index') %>
        <%= link_to "Details", controller: 'markets', action: 'show', id: market.id %>
      <% end %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>

app/views/shared/_all_vendors.html.erb
  <table>
    <tr>
      <th>Vendor Name</th>
    </tr>
    <% @vendors.each do |vendor| %>
    <tr>
      <td><%= link_to "#{vendor.name.titlecase}", "#{@path}/#{vendor.id}" %> </td>
    </tr>
    <% end %>
  </table>

app/views/shared/_each_product.html.erb
<table class="details">
  <tr>
    <th>Id</th>
    <td><%= @product.id %></td>
  </tr>
  <tr>
    <th>Vendor Name</th>
    <td><%= @product.name.titlecase %></td>
  </tr>
  <tr>
    <th>Vendor Id</th>
    <td><%= @product.vendor_id%></td>
  </tr>
</table>

app/views/shared/_each_vendor.html.erb
<table class="details">
  <tr>
    <th>Id</th>
    <td><%= @vendor.id %></td>
  </tr>
  <tr>
    <th>Vendor Name</th>
    <td><%= @vendor.name.titlecase %></td>
  </tr>
  <tr>
    <th>No. of Employees</th>
    <td><%= @vendor.no_of_employees %></td>
  </tr>
  <tr>
    <th> Market Id</th>
        <td> <%= @vendor.market_id %> </td>
  </tr>
</table>

app/views/shared/_header.html.erb
<header>

  <%= link_to "Home", root_path, method: :get%>
  <%= link_to "Market Portal", market_portal_path, method: :get %>
  <%= link_to "Vendor Portal", vendors_path, method: :get %>

 </header>

app/views/shared/_index_vendors.html.erb
<ul>
  <% vendors.each do |vendor| %>
    <% unless vendor.archived %>
      <li><%= vendor.name %></li>
    <% end %>
  <% end %>
</ul>

app/views/shared/_market_details.html.erb
<ul>

  <% details.each do |detail, value| %> 

 <li>

   <%= "#{detail}: #{value}" %>

 </li>


<% end%>

</ul>

app/views/shared/_market_form.html.erb
<%= form_for @market do |f| %>

  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :street_address %>
    <%= f.text_field :street_address %>

    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :county %>
    <%= f.text_field :county %>

    <%= f.label :state %>
    <%= f.text_field :state %>

    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </fieldset>

  <%= f.submit %>

<% end %>

app/views/shared/_product_form.html.erb
<%= form_for @product do |f| %>

  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.hidden_field :vendor_id %>

  </fieldset>

  <%= f.submit %>

<% end %>

app/views/shared/_sales_table.html.erb
<table>
  <thead>
    <tr>
      <th>Time of Purchase</th>
      <th>Product</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <% sales.each do |sale| %>
      <tr>
        <td><%= format_datetime(sale.purchase_time.to_datetime) %></td>
        <td><%= Product.find(sale.product_id).name %></td>
        <td class="financial"><%= format_money(sale.amount) %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th colspan="2">Sales Total</th>
      <td class="financial"><%= format_money(Sale.sum_amount(sales)) %></td>
    </tr>
  </tfoot>
</table>

app/views/shared/_show_market.html.erb
<ul>
  <li>Name: <%= market.name %></li>
  <li>Address: <%= market.address %></li>
  <li>City, State Zip: <%= "#{market.city}, #{market.state} #{market.zip}" %></li>
  <li>County: <%= market.county %></li>
</ul>

app/views/shared/_show_vendors.html.erb
<% if current_page?(controller: 'markets', action: 'vendors_index') %>
  <div class="button_block">
    <%= link_to 'Create Vendor', new_vendor_path(market_id: params[:id]) %>
  </div>
<% end %>
<h1>Vendors at <%= @market.name %></h1>

<div class="button_block">
  <% if current_page?(controller: 'users', action: 'vendors') %>
    <%= link_to "Back to #{@market.name} Information", market_users_path, method: :get %>
  <% elsif current_page?(controller: 'markets', action: 'vendors_index')%>
    <%= link_to "Back to #{@market.name} Information", market_path, method: :get %>
  <% end %>
</div>

<table>
<tr>
  <th>
    ID
  </th>
  <th>
    Name
  </th>
  <% if current_page?(controller: 'markets', action: 'vendors_index')%>
    <th class="center">
      Details
    </th>
  <% end %>
  </tr>
<tbody>
  <% @vendors.each do |vendor| %>
  <tr>
    <td>
      <%= vendor.id %>
    </td>
    <td>
      <%= vendor.name %>
    </td>
    <% if current_page?(controller: 'markets', action: 'vendors_index')%>
      <td class="center">
        <%= link_to "Details", vendor_path(id: vendor.id, params: { market_user: true, market_id: params[:id] } ) %>
      </td>
    <% end %>
    </tr>
  <% end %>
</tbody>
</table>

app/views/shared/_vendor_form.html.erb
<%= form_for @vendor, url: @url, method: @method do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :num_of_employees %>
  <%= f.text_field :num_of_employees %>

  <%= f.hidden_field :market_id, :value => params[:market_id] %>

  <%= f.submit %>

  <% end %>